---
title: "Creating multi-panel plots"
engine: julia
julia:
  exeflags: ["--project", "--threads=auto"]
---

::: {.objectives title="Learning objectives"} 
After working through this page you will be able to:

- build a tidy summary `DataFrame` suitable for plotting;
- compose a multi-panel figure with [AlgebraOfGraphics](../reference/useful_packages.qmd);
- reproduce a publication-style faceted plot.
:::

::: {.callout-note title="Before you start"}
**Prerequisites:** [Analysis of the sleepstudy data](../lmm-intro/sleepstudy.qmd) for the modeling vocabulary; see also [Useful packages](../reference/useful_packages.qmd) for the plotting stack.

**Datasets used:** `fggk21` (see the [dataset catalog](../getting-started/datasets.qmd)).
:::

This notebook shows creating a multi-panel plot similar to Figure 2 of @Fuehner2021.

The data are available from the SMLP2026 example datasets.

```{julia}
#| code-fold: true
using Arrow
using AlgebraOfGraphics
using CairoMakie   # for displaying static plots
using DataFrames
using Statistics
using StatsBase
using SMLP2026: dataset
```

```{julia}
tbl = dataset("fggk21")
```

```{julia}
typeof(tbl)
```

```{julia}
df = DataFrame(tbl)
typeof(df)
```

# Creating a summary data frame

The response to be plotted is the mean score by `Test` and `Sex` and `age`, rounded to the nearest 0.1 years.

The first task is to round the `age` to 1 digit after the decimal place, which can be done with `select` applied to a `DataFrame`.
In some ways this is the most complicated expression in creating the plot so we will break it down.
`select` is applied to `DataFrame(dat)`, which is the conversion of the `Arrow.Table`, `dat`, to a `DataFrame`.
This is necessary because an `Arrow.Table` is immutable but a `DataFrame` can be modified.

The arguments after the `DataFrame` describe how to modify the contents.
The first `:` indicates that all the existing columns should be included.
The other expression can be pairs (created with the `=>` operator) of the form `:col => function` or of the form `:col => function => :newname`.
(See the [documentation of the DataFrames package](http://juliadata.github.io/DataFrames.jl/stable/) for details.)

```{julia}
transform!(df, :age, :age => ByRow(x -> x - 8.5) => :a1) # centered age (linear)
select!(groupby(df, :Test), :, :score => zscore => :zScore) # z-score
tlabels = [     # establish order and labels of tbl.Test
  "Run" => "Endurance",
  "Star_r" => "Coordination",
  "S20_r" => "Speed",
  "SLJ" => "PowerLOW",
  "BPT" => "PowerUP",
];
```

The next stage is a *group-apply-combine* operation to group the rows by `Sex`, `Test` and `rnd_age` then apply `mean` to the `zScore` and also apply `length` to `zScore` to record the number in each group.

```{julia}
df2 = combine(
  groupby(
    select(df, :, :age => ByRow(x -> round(x; digits=1)) => :age),
    [:Sex, :Test, :age],
  ),
  :zScore => mean => :zScore,
  :zScore => length => :n,
)
```

# Creating the plot

The `AlgebraOfGraphics` package applies operators to the results of functions such as `data` (specify the data table to be used), `mapping` (designate the roles of columns), and `visual` (type of visual presentation).

```{julia}
let
  design = mapping(:age => "Age", 
                   :zScore => "Z Score"; 
                   color=:Sex, 
                   col=:Test => renamer(tlabels))
  lines = design * linear()
  means = design * visual(Scatter; markersize=5)
  draw(data(df2) * means + data(df) * lines)
end
```

  <!-- 
  TODO 
  - TBD: Relabel factor levels (Boys, Girls; fitness components for Test)
  - TBD: Relevel factors; why not levels from Tables?
  - TBD: Set range (7.8 to 9.2) and tick marks (8, 8.5, 9) of axes.
  - TBD: Move legend in plot? 
  -->

::: {#refs}
:::

## Exercises

1. **Save the figure.** Write the final figure to a PNG file at a chosen resolution.

::: {.callout-note collapse="true" title="Solution"}
`draw` returns a Makie figure-axis-legend object; `save` writes it out.

```{julia}
#| eval: false
fg = draw(plt)            # plt = your AlgebraOfGraphics layer expression
save("fggk21_panels.png", fg; px_per_unit=2)
```
:::

---

*This page was rendered from git revision {{< git-rev short=true >}} using Quarto {{< version >}} and Julia {{< julia-version >}}.*
